name = "oracle-api"
compatibility_date = "2022-09-11"
node_compat = true

[vars]
# This is a private key used during development.
# In production, you must set one using:
# echo "$PRIVATE_KEY" | wrangler secret put PRIVATE_KEY
PRIVATE_KEY = "0x57678cb3021a7aa39d08839ea7d47ea0246a6f27a0cde894e732a02ee95f20ea"