name = "oracle-api"
compatibility_date = "2022-09-11"
node_compat = true
main = 'src/index.ts'


# 
# Development.
# 

[env.development.vars]
WORKER_ENV = "development"
PRIVATE_KEY = "0x57678cb3021a7aa39d08839ea7d47ea0246a6f27a0cde894e732a02ee95f20ea" # Relayer: 0x2E88a4822f6C1f19043B90C8dd51a27B1258FF90

# 
# Staging.
# 

[env.staging.vars]
WORKER_ENV = "staging"
PRIVATE_KEY = "0x57678cb3021a7aa39d08839ea7d47ea0246a6f27a0cde894e732a02ee95f20ea" # Relayer: 0x2E88a4822f6C1f19043B90C8dd51a27B1258FF90


# 
# Production.
# 

[env.production.vars]
WORKER_ENV = "production"
# These must be set using `wrangler secret put`.
# e.g. `echo "0x57678cb3021a7aa39d08839ea7d47ea0246a6f27a0cde894e732a02ee95f20ea" | wrangler secret put PRIVATE_KEY`.
# - PRIVATE_KEY






[env.development]
name = "oracle-development"
[env.staging]
name = "oracle-staging"
[env.production]
name = "oracle-production"
